services:
  smartlocker-app:
    container_name: smartlocker-app
    image: caio96k/smartlocker-app:1.0
    ports:
      - "3000:3000"
    volumes:
      - /media/2tera/aplicativos/smartlocker-app/app:/app
      - /media/2tera/aplicativos/smartlocker-app/bundle:/usr/local/bundle
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWD: postgres
        POSTGRES_HOST: database
    command: ["bash", "-c", "bundle install && rails server -b 0.0.0.0"]
