version: "3"

volumes:
  db_data:
  web-bundle:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "sh -c 'rm -f tmp/pids/server.pid && (bundle check || bundle install) && bundle exec rails s -b 0.0.0.0'"
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - web-bundle:/usr/local/bundle
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWD: postgres
        POSTGRES_HOST: database

  database:
    image: postgres:15.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres