default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: smartlocker_development

  
test:
  <<: *default
  database: smartlocker_test


production:
  <<: *default
  database: smartlocker_production
  username: smartlocker
  password: <%= ENV["SMARTLOCKER_DATABASE_PASSWORD"] %>
  

